#!/usr/bin/env python3
"""
Render a markdown preview from the unified analysis JSON.

Pure Python — no LLM call. Reads the output of analyze_podcast.py
and produces a clean, readable markdown file focused on interesting ideas.
"""

import argparse
import json
import os
import sys
from pathlib import Path


def load_analysis(path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def parse_timestamp(ts_str):
    """Convert [HH:MM:SS] or HH:MM:SS to seconds for YouTube link."""
    ts = ts_str.strip('[]')
    parts = ts.split(':')
    if len(parts) == 3:
        h, m, s = map(int, parts)
        return h * 3600 + m * 60 + s
    elif len(parts) == 2:
        m, s = map(int, parts)
        return m * 60 + s
    return 0


def render_markdown(data, youtube_id=None):
    title = data.get("title") or "Podcast Analysis"
    type_primary = data.get("type_primary", "Unknown")
    type_secondary = data.get("type_secondary", "")
    language = data.get("language", "")
    duration = data.get("duration_minutes_estimate")
    summary = data.get("summary", "")
    chapters = data.get("chapters", [])
    insights = data.get("top_insights", [])
    themes = data.get("key_themes", [])

    md = []

    # YouTube embed
    if youtube_id:
        md.append(f"<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/{youtube_id}\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>")
        md.append("")

    # Header
    md.append(f"# {title}")
    md.append("")
    meta_parts = [f"**Format:** {type_primary}"]
    if type_secondary:
        meta_parts[0] += f" / {type_secondary}"
    if language:
        meta_parts.append(f"**Language:** {language}")
    if duration:
        meta_parts.append(f"**Duration:** {duration:.0f} min")
    md.append(" | ".join(meta_parts))
    md.append("")

    # Summary
    if summary:
        md.append("## Summary")
        md.append("")
        md.append(summary)
        md.append("")

    # Top insights — the main event
    if insights:
        md.append("## Top Insights")
        md.append("")
        for i, ins in enumerate(insights, 1):
            ts = ins.get("timestamp", "")
            speaker = ins.get("speaker", "")
            formulation = ins.get("formulation", "")
            explanation = ins.get("explanation", "")

            speaker_str = f" ({speaker})" if speaker and speaker != "unknown" else ""
            md.append(f"### {i}.")
            md.append("")
            if ts:
                md.append(f"> [{ts}]{speaker_str}")
                md.append(">")
            if formulation:
                md.append(f"> *\"{formulation}\"*")
            md.append("")
            if explanation:
                md.append(explanation)
                md.append("")

    # Chapter guide
    if chapters:
        md.append("## Chapters")
        md.append("")
        md.append("| # | Time | Title | Summary |")
        md.append("|---|------|-------|-----------|")
        for ch in chapters:
            idx = ch.get("index", "")
            start_raw = ch.get("start", "").strip("[]")
            end_raw = ch.get("end", "").strip("[]")
            time_range = f"{start_raw}–{end_raw}" if start_raw and end_raw else start_raw or end_raw
            ch_title = ch.get("title", "")
            ch_summary = ch.get("summary", "").replace("\n", " ")
            
            # Make timestamp a YouTube link
            if youtube_id and start_raw:
                seconds = parse_timestamp(start_raw)
                yt_link = f"https://youtu.be/{youtube_id}?t={seconds}"
                time_range = f"[{time_range}]({yt_link})"
            
            md.append(f"| {idx} | {time_range} | {ch_title} | {ch_summary} |")
        md.append("")

    # Key themes
    if themes:
        md.append("## Key Themes")
        md.append("")
        md.append(", ".join(themes))
        md.append("")

    # Footer
    model = data.get("model_used", "")
    tokens = data.get("tokens_used", {}).get("total", "")
    if model or tokens:
        md.append("---")
        footer_parts = ["_Generated by Podscript_"]
        if model:
            footer_parts.append(f"_Model: {model}_")
        if tokens:
            footer_parts.append(f"_Tokens: {tokens}_")
        md.append(" · ".join(footer_parts))
        md.append("")

    return "\n".join(md)


def derive_preview_path(analysis_path):
    """Derive preview output path from analysis JSON path."""
    p = Path(analysis_path)
    name = p.stem
    if name.endswith("_analysis"):
        return str(p.parent / (name[: -len("_analysis")] + "_preview.md"))
    return str(p.parent / (name + "_preview.md"))


def main():
    parser = argparse.ArgumentParser(
        description="Render markdown preview from unified analysis JSON",
    )
    parser.add_argument("analysis_json", help="Path to analysis JSON (output of analyze_podcast.py)")
    parser.add_argument("--output", help="Custom output path (default: derived from input)")
    parser.add_argument("--youtube-id", help="YouTube video ID for embed and timestamp links")
    args = parser.parse_args()

    if not os.path.exists(args.analysis_json):
        print(f"File not found: {args.analysis_json}")
        sys.exit(1)

    data = load_analysis(args.analysis_json)
    md = render_markdown(data, youtube_id=args.youtube_id)

    output_path = args.output or derive_preview_path(args.analysis_json)
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(md)

    print(f"Preview saved to: {output_path}")


if __name__ == "__main__":
    main()
